import { defineConfig } from 'vite-plus';

const generatedIgnoreGlobs = [
  '**/node_modules/**',
  '**/dist/**',
  'apps/mobile/www/**',
  'apps/mobile/android/**',
];

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    ignorePatterns: generatedIgnoreGlobs,
    printWidth: 80,
    proseWrap: 'never',
    semi: true,
    singleQuote: true,
    sortPackageJson: false,
    trailingComma: 'all',
    overrides: [
      {
        files: [
          '*.json',
          '*.json5',
          '*.jsonc',
          '*.code-workspace',
          '**/*.json',
          '**/*.json5',
          '**/*.jsonc',
          '**/*.code-workspace',
        ],
        options: {
          trailingComma: 'none',
        },
      },
    ],
  },
  lint: {
    ignorePatterns: generatedIgnoreGlobs,
    options: { typeAware: true, typeCheck: true },
    categories: {
      correctness: 'error',
      suspicious: 'warn',
    },
    env: {
      browser: true,
      es2021: true,
      node: true,
    },
    globals: {
      document: 'readonly',
      navigator: 'readonly',
      window: 'readonly',
    },
    jsPlugins: [
      {
        name: 'command',
        specifier: 'eslint-plugin-command',
      },
      {
        name: 'eslint-comments',
        specifier: '@eslint-community/eslint-plugin-eslint-comments',
      },
    ],
    plugins: [
      'import',
      'node',
      'oxc',
      'typescript',
      'unicorn',
      'vitest',
      'vue',
    ],
    rules: {
      'accessor-pairs': [
        'error',
        {
          enforceForClassMembers: true,
          setWithoutGet: true,
        },
      ],
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'command/command': 'error',

      'default-case-last': 'error',
      eqeqeq: ['error', 'always'],
      'eslint-comments/no-aggregating-enable': 'error',
      'eslint-comments/no-duplicate-disable': 'error',
      'eslint-comments/no-unlimited-disable': 'error',
      'eslint-comments/no-unused-enable': 'error',
      'eslint/no-unreachable': 'error',

      'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-as-default': 'off',
      'import/no-named-as-default-member': 'off',
      'import/no-named-default': 'error',
      'import/no-self-import': 'error',
      'import/no-unassigned-import': 'off',
      'import/no-webpack-loader-syntax': 'error',
      'node/no-exports-assign': 'error',
      'node/no-new-require': 'error',
      'node/no-path-concat': 'error',
      'new-cap': [
        'error',
        {
          capIsNew: false,
          newIsCap: true,
          properties: true,
        },
      ],
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'no-control-regex': 'off',
      'no-debugger': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-fallthrough': 'error',
      'no-new-func': 'error',
      'no-object-constructor': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-lone-blocks': 'error',
      'no-multi-str': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-proto': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': ['error', { builtinGlobals: false }],
      'no-regex-spaces': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'eslint/no-empty-function': [
        'error',
        {
          allow: ['arrowFunctions', 'functions', 'methods'],
        },
      ],
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTaggedTemplates: true,
          allowTernary: true,
        },
      ],
      'eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      'no-var': 'error',
      'no-eval': 'error',
      'no-iterator': 'error',
      'no-new-wrappers': 'error',
      'no-restricted-globals': [
        'error',
        { message: 'Use `globalThis` instead.', name: 'global' },
        { message: 'Use `globalThis` instead.', name: 'self' },
      ],
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-return': 'error',
      'prefer-const': [
        'error',
        {
          destructuring: 'all',
          ignoreReadBeforeAssign: true,
        },
      ],
      'prefer-exponentiation-operator': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'symbol-description': 'error',
      'unicode-bom': ['error', 'never'],
      'use-isnan': [
        'error',
        {
          enforceForIndexOf: true,
          enforceForSwitchCase: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: true,
        },
      ],
      'vars-on-top': 'error',
      yoda: ['error', 'never'],
      'typescript/ban-ts-comment': 'error',
      // Keep the first type-aware rollout conservative. These rules currently
      // produce high-volume diagnostics and need file-by-file cleanup later.
      'typescript/await-thenable': 'off',
      'typescript/no-base-to-string': 'off',
      'typescript/no-duplicate-type-constituents': 'off',
      'typescript/no-floating-promises': 'off',
      'typescript/no-misused-spread': 'off',
      'typescript/no-non-null-assertion': 'error',
      'typescript/no-redundant-type-constituents': 'off',
      'typescript/no-unnecessary-boolean-literal-compare': 'off',
      'typescript/no-unnecessary-type-assertion': 'off',
      'typescript/no-unnecessary-type-arguments': 'off',
      'typescript/no-unnecessary-template-expression': 'off',
      'typescript/no-unsafe-enum-comparison': 'off',
      'typescript/no-unsafe-type-assertion': 'off',
      'typescript/no-var-requires': 'error',
      'typescript/restrict-template-expressions': 'off',
      'typescript/triple-slash-reference': 'error',
      'typescript/unbound-method': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'unicorn/no-process-exit': 'error',
      'unicorn/no-single-promise-in-promise-methods': 'off',
      'unicorn/no-useless-spread': 'off',
      'unicorn/prefer-global-this': 'off',
      'unicorn/prefer-module': 'error',
      'vue/prefer-import-from-vue': 'error',
      'jest/no-conditional-expect': 'off',
      'jest/require-to-throw-message': 'off',
      'vitest/consistent-test-it': [
        'error',
        {
          fn: 'it',
          withinDescribe: 'it',
        },
      ],
      'vitest/hoisted-apis-on-top': 'off',
      'vitest/no-focused-tests': 'error',
      'vitest/no-identical-title': 'error',
      'vitest/no-import-node-test': 'error',
      'vitest/prefer-hooks-in-order': 'error',
      'vitest/prefer-lowercase-title': 'error',
      'vitest/require-mock-type-parameters': 'off',
    },
    overrides: [
      {
        files: ['*.d.ts', '**/*.d.ts'],
        rules: {
          'import/no-unassigned-import': 'off',
          'typescript/triple-slash-reference': 'off',
        },
      },
      {
        files: [
          '**/tests/**/*.js',
          '**/tests/**/*.cjs',
          '**/tests/**/*.mjs',
          '**/tests/**/*.jsx',
          '**/tests/**/*.ts',
          '**/tests/**/*.cts',
          '**/tests/**/*.mts',
          '**/tests/**/*.tsx',

          '**/__tests__/**/*.js',
          '**/__tests__/**/*.cjs',
          '**/__tests__/**/*.mjs',
          '**/__tests__/**/*.jsx',
          '**/__tests__/**/*.ts',
          '**/__tests__/**/*.cts',
          '**/__tests__/**/*.mts',
          '**/__tests__/**/*.tsx',
          '**/*.spec.js',
          '**/*.spec.cjs',
          '**/*.spec.mjs',
          '**/*.spec.jsx',
          '**/*.spec.ts',
          '**/*.spec.cts',
          '**/*.spec.mts',
          '**/*.spec.tsx',
          '**/*.test.js',
          '**/*.test.cjs',
          '**/*.test.mjs',
          '**/*.test.jsx',
          '**/*.test.ts',
          '**/*.test.cts',
          '**/*.test.mts',
          '**/*.test.tsx',
          '**/*.bench.js',
          '**/*.bench.cjs',
          '**/*.bench.mjs',
          '**/*.bench.jsx',
          '**/*.bench.ts',
          '**/*.bench.cts',
          '**/*.bench.mts',
          '**/*.bench.tsx',
          '**/*.benchmark.js',
          '**/*.benchmark.cjs',
          '**/*.benchmark.mjs',
          '**/*.benchmark.jsx',
          '**/*.benchmark.ts',
          '**/*.benchmark.cts',
          '**/*.benchmark.mts',
          '**/*.benchmark.tsx',
        ],
        rules: {
          'no-console': 'off',
        },
      },
      {
        files: ['apps/electron/**/*'],
        rules: {
          'no-console': 'off',
          'import/no-self-import': 'off',
          'unicorn/prefer-module': 'off',
        },
      },
      {
        files: ['packages/vite-electron-plugin/**/*'],
        rules: {
          'no-process-exit': 'off',
        },
      },
      {
        files: ['packages/capacitor-electron/**/*'],
        rules: {
          'no-useless-return': 'off',
        },
      },
      {
        files: ['packages/@core/ui-kit/menu-ui/src/sub-menu.vue'],
        rules: {
          'import/no-self-import': 'off',
        },
      },
      {
        files: [
          'scripts/**/*.js',
          'scripts/**/*.cjs',
          'scripts/**/*.mjs',
          'scripts/**/*.jsx',
          'scripts/**/*.ts',
          'scripts/**/*.cts',
          'scripts/**/*.mts',
          'scripts/**/*.tsx',
          'internal/**/*.js',
          'internal/**/*.cjs',
          'internal/**/*.mjs',
          'internal/**/*.jsx',
          'internal/**/*.ts',
          'internal/**/*.cts',
          'internal/**/*.mts',
          'internal/**/*.tsx',
        ],
        rules: {
          'no-console': 'off',
          'unicorn/no-process-exit': 'off',
        },
      },
    ],
  },
  run: {
    cache: true,
  },
});
